[package]
name = "stargazer-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "*"
actix-web = "*"
actix-web-actors = "*"
anyhow = "*"
serde = { version = "*",  features = ["derive"] }
serde_json = "*"
log = "*"
