[package]
name = "stargazer-rs"
version = "0.1.0"
edition = "2018"

[lib]
name = "stargazer_lib"
path = "src/lib/lib.rs"

[[bin]]
name = "stargazer"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.12"
actix-web = "4.0.0-beta.8"
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"