on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Test

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout 🛎️
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-stable-${{ hashFiles('**/Cargo.lock') }}-lint
      - uses: actions-rs/toolchain@v1
        name: Setup Cargo Toolchain 🛎️
        with:
          components: rustfmt, clippy
          toolchain: stable
          default: true
      - uses: actions-rs/cargo@v1
        name: Check Code Format 🔧
        with:
          command: fmt
          args: -- --check
      - uses: actions-rs/cargo@v1
        name: Run Clippy Lints 🔨
        with:
          command: clippy
          args: --all-targets

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout 🛎️
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-stable-${{ hashFiles('**/Cargo.lock') }}-test-tokio
      - uses: actions-rs/toolchain@v1
        name: Setup Cargo Toolchain 🛎️
        with:
          profile: minimal
          toolchain: stable
          default: true
      - uses: actions-rs/cargo@v1
        name: Running Tests 🚀
        with:
          command: test
          args: --workspace